// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: '215363675734',
    projectId: 'fir-acc9d',
    authDomain: 'fir-acc9d.firebaseapp.com',
    databaseURL: 'your database url',
    storageBucket: 'fir-acc9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: '215363675734',
    projectId: 'fir-acc9d',
    databaseURL: 'your database url',
    storageBucket: 'fir-acc9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: '215363675734',
    projectId: 'fir-acc9d',
    databaseURL: 'https://fir-acc9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-acc9d.firebasestorage.app',
    iosBundleId: 'com.example.smartRoomMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: '215363675734',
    projectId: 'fir-acc9d',
    databaseURL: 'your database url',
    storageBucket: 'fir-acc9d.firebasestorage.app',
    iosBundleId: 'com.example.smartRoomMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api key',
    appId: 'your app id',
    messagingSenderId: '215363675734',
    projectId: 'fir-acc9d',
    authDomain: 'fir-acc9d.firebaseapp.com',
    databaseURL: 'your database url',
    storageBucket: 'fir-acc9d.firebasestorage.app',
  );
}
